### ISSUE TITLE
not highlight

### ISSUE THREAD

**Issue by flavioeverardo** [santifa/pasp-mode#1]
Hi there,

first of all thanks for implementing this asp-mode.
just a minor thing. I was using the predicate "noteValue" in one of my programs and the not was red highlighted. 

I have given a space in the pasp-mode.el in the lines 150 and 162 like so:
      '(("not " . font-lock-negation-char-face)

So far now I can highlight the default negation when used as it and not as part of any predicate, atom, etc.
I'm not expert on this and you might know a lot better than me about how this emacs file works but I hope that doesn't change any other feature.

Regards
Flavio
any comment, let me know at flavio.everardo@cs.uni-potsdam.de

**Comment by santifa** [comment]
Hi,
thanks for the issue.
I reworked parts of the syntax highlighting and integrated your finding.
